title: "Llama Studios"
logo: "https://avatars.githubusercontent.com/u/65722273?s=200&v=4"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

aux_links:
  "YouTube":
    - "https://www.youtube.com/channel/UCELAdQLU7zQZdSjoHk9fAAA"
  "MCPEDL":
    - "https://mcpedl.com/user/kyleplo/"
  "Discord":
    - "https://discord.com/invite/V95XT2zuWx"

aux_links_new_tab: true

footer_content: Llama Studios is not at all affiliated with Mojang Studios, Minecraft, or Microsoft.
